#!/command/with-contenv bash

source /assets/functions/00-container
set -a
prepare_service
set +a
PROCESS_NAME="argus"

bootstrap_filesystem
configure_argus
custom_files "${CONTAINER_CUSTOM_PATH}" /
custom_scripts "${CONTAINER_CUSTOM_SCRIPTS_PATH}"
liftoff
